server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"
  env: "development"

database:
  user: "postgres"
  password: "password"
  name: "task_manager"
  host: "localhost"
  port: "5432"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

auth:
  jwt_secret: "your_very_secure_jwt_secret_key"
  jwt_access_expires_in: "15m"
  jwt_refresh_expires_in: "24h"